### ISSUE TITLE
Doesn't compile on Swift 2

### ISSUE THREAD

**Issue by jkhustler** [puffinsupply/Restraint#2]

**Comment by soopa** [comment]
Thanks @jkhustler! I've migrated the project to Swift 2 (with Xcode 7 Beta 3) in the following branch: https://github.com/puffinsupply/Restraint/tree/am/swift-2

Will merge after Xcode 7 release.

**Comment by soopa** [comment]
@jkhustler added some additional updates for Swift 2 that increase the flexibility allowing use of iOS 9 layout guides. Enjoy!

**Comment by jkhustler** [comment]
@soopa awesome! :+1: for being easy to understand and simple to use btw.
