### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [puffinsupply/Restraint#5]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by cwalo** [comment]
Updated to latest Swift 3 syntax. See #6 
Note that, for now, you'll need to specify either `"master"` or the latest commit in your Cartfile to compile for Swift 3.

**Comment by lfarah** [comment]
Thank you, @cwalo! 🎉

**Comment by soopa** [comment]
thanks @lfarah!

thanks @cwalo!
